apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workflow2
  labels:
    app: test-workflow2
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717493941473
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workflow2
  template:
    metadata:
      labels:
        app: test-workflow2
    spec:
      containers:
        - name: test-workflow2
          image: acr332.azurecr.io/image-workflow-1717493941473:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
