apiVersion: v1
kind: Service
metadata:
  name: test-workflow2
  namespace: namespace-workflow-1717493941473
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-workflow2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80